### ISSUE TITLE
Energized Protection Checking Domains

### ISSUE THREAD

**Issue by AdroitAdorKhan** [bjornstar/hosts#19]
Hey, these following domains were intended to use in Energized Protection Web [Check](https://energized.pro/check) page, to let users know whether the pack was applied properly or which pack/extension they are using. They contain nothing but a webpage to let users know they aren't using that specific pack. Which were meant to be included in our lists only.

```
0.0.0.0	watchdog.energized.pro
0.0.0.0	watchdog-basic.energized.pro
0.0.0.0	watchdog-blu.energized.pro
0.0.0.0	watchdog-blugo.energized.pro
0.0.0.0	watchdog-dns.energized.pro
0.0.0.0	watchdog-ext.energized.pro
0.0.0.0	watchdog-porn.energized.pro
0.0.0.0	watchdog-spark.energized.pro
0.0.0.0	watchdog-ultimate.energized.pro
0.0.0.0	watchdog-unified.energized.pro
```

It would be nice if you can whitelist them from your lists. Thanks.

**Comment by bjornstar** [comment]
Your check page gives the false impression that you are "secure" if some `energized.pro` subdomains are blocked. It is not testing if your users are actually protected from any objectionable hosts.

My suggestion to you is to perform tests against entries on your lists rather than taking a shortcut.
