### ISSUE TITLE
Blocking www.privateinternetaccess.com

### ISSUE THREAD

**Issue by p1r473** [bjornstar/hosts#6]
Why are you filtering out VPN providers?
This is a legit company...

**Comment by preachermanx** [comment]
Mt. Gox?

**Comment by bjornstar** [comment]
As I explained in #5, hosts get added to my list when they advertise on other sites. Typically if a third party host is referenced and does not appear to be required for a site or application to work it gets blocked.

I don't mind removing it, but if people just ask me why it's being blocked all I can do is answer their question.

Would you like it unblocked?

**Comment by p1r473** [comment]
Yes please, I dont believe they are hosting their own ads

**Comment by p1r473** [comment]
Hi @bjornstar this is still being blocked in the list... maybe your fix was reverted? 
https://github.com/bjornstar/hosts/blob/master/hosts#L3660

**Comment by bjornstar** [comment]
> Hi @bjornstar this is still being blocked in the list... maybe your fix was reverted?
> https://github.com/bjornstar/hosts/blob/master/hosts#L3660

It looks like it got re-added soon after it was removed alongside many other advertising sites: https://github.com/bjornstar/hosts/commit/9d3694d3d4b513aaf91e2f3af96bb27fc6b2687b

This would indicate that they are advertising on sites that I visit. I can remove it again, but I can't promise that it won't show up again. I'll put a note by it and hopefully I can at least point out which site it was advertising on the next time it gets added.

The best course of action would be for PIA to stop using their official website domain for advertising. They should use a dedicated subdomain for advertising purposes so that when they get blocked it doesn't affect how people access their service.

Barring that, you can add it to your own whitelist so that when it gets blocked again it won't affect you.

**Comment by p1r473** [comment]
Thanks

**Comment by p1r473** [comment]
No way from committing it on your end in the future?

**Comment by bjornstar** [comment]
> No way from committing it on your end in the future?

You'd like me to maintain your personal whitelist?

**Comment by p1r473** [comment]
No. If you know this is a false positive, and you commit the changes, cant you just not re-commit it?

**Comment by bjornstar** [comment]
I manually add domains to this list when I see traffic to them from sites that I visit. I don't consider it a false positive when I see it serving an ad on a site I visit.

I generously removed the domain from my list twice now. I'm not going to stop blocking their ads when I see them.

**Comment by p1r473** [comment]
Understood, thanks
